#pragma once

#define COPYBASKET_VERSION_MAJOR 1
#define COPYBASKET_VERSION_MINOR 5
#define COPYBASKET_VERSION_PATCH 0
#define COPYBASKET_VERSION_BUILD 0

#define COPYBASKET_STR_HELPER(x)  #x
#define COPYBASKET_STR(x)         COPYBASKET_STR_HELPER(x)
#define COPYBASKET_WSTR_HELPER(x) L#x
#define COPYBASKET_WSTR(x)        COPYBASKET_WSTR_HELPER(x)

#define COPYBASKET_VERSION_STR_A \
    COPYBASKET_STR(COPYBASKET_VERSION_MAJOR) "." \
    COPYBASKET_STR(COPYBASKET_VERSION_MINOR) "." \
    COPYBASKET_STR(COPYBASKET_VERSION_PATCH)

#define COPYBASKET_VERSION_STR \
    COPYBASKET_WSTR(COPYBASKET_VERSION_MAJOR) L"." \
    COPYBASKET_WSTR(COPYBASKET_VERSION_MINOR) L"." \
    COPYBASKET_WSTR(COPYBASKET_VERSION_PATCH)
